language: node_js
node_js:
  - 8
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1366x768x24 > /dev/null 2>&1 &
  - npm i vuepress macaca-ecosystem
  # https://github.com/webpack-contrib/terser-webpack-plugin/issues/66
  - npm i terser@3.14.1
  - npm run docs:build
script:
  - npm i
  - $(npm bin)/macaca-ecosystem push --cwd ./docs_dist --branch gh-pages
  - npm run lint
  - npm run test
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
